version: 2
jobs:
  test:
    docker:
      - image: adambene/circleci-openjdk-awscli
    working_directory: ~/bootcamp-circle-cloudformation
    steps:
      - checkout
      - run: sbt test
  deploy:
    docker:
      - image: adambene/circleci-openjdk-awscli
    working_directory: ~/bootcamp-circle-cloudformation
    steps:
      - checkout
      - run: ./build-and-deploy-to-aws.sh zsolt-auto-scaling-AutoScalingGroup-N7OVD5WRUKA8 zsolt

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test